### ISSUE TITLE
Nav Bar Links

### ISSUE THREAD

**Issue by Tereseus** [GRudinsky/ColmarAcademy#2]
Your nav bar links refresh the page. While they are not supposed to link to any part of the page at the moment they also shouldn't refresh the page. Simply make them link to the top section of your page for the moment. Good job getting href to work though.

**Comment by GRudinsky** [comment]
I just wanted to link them somewhere and didn't want to leave href blank in order to check if it works.

**Comment by GRudinsky** [comment]
links changed and are not refreshing now.
