### ISSUE TITLE
Video Controls

### ISSUE THREAD

**Issue by Tereseus** [GRudinsky/ColmarAcademy#3]
Your video does not have video controls and because of this the video starts to play as soon as the page is loaded. If you insert video controls you can pause/start and set the volume of the video. A simple feature that makes a big difference.

**Comment by GRudinsky** [comment]
I thought this isn't needed since the video isn't at all informative and has no sound anyway. if it was someone's speech or interview - controls would have been included.

**Comment by GRudinsky** [comment]
Video controls added.
